// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function DownloadVersion(arg1, arg2) {
  return window['go']['main']['App']['DownloadVersion'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetLogsSince(arg1) {
  return window['go']['main']['App']['GetLogsSince'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetVersions() {
  return window['go']['main']['App']['GetVersions']();
}

export function HasFrpc() {
  return window['go']['main']['App']['HasFrpc']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartFrpc() {
  return window['go']['main']['App']['StartFrpc']();
}

export function StopFrpc() {
  return window['go']['main']['App']['StopFrpc']();
}

export function UninstallFrpc() {
  return window['go']['main']['App']['UninstallFrpc']();
}
