// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearLogs():Promise<void>;

export function DownloadVersion(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetConfig():Promise<Record<string, any>>;

export function GetLogs():Promise<Array<main.logEntry>>;

export function GetLogsSince(arg1:number):Promise<Array<main.logEntry>>;

export function GetSettings():Promise<main.Settings>;

export function GetStatus():Promise<Record<string, any>>;

export function GetVersions():Promise<Record<string, any>>;

export function HasFrpc():Promise<Record<string, any>>;

export function SaveConfig(arg1:string):Promise<Record<string, any>>;

export function SaveSettings(arg1:main.Settings):Promise<Record<string, any>>;

export function StartFrpc():Promise<Record<string, any>>;

export function StopFrpc():Promise<Record<string, any>>;

export function UninstallFrpc():Promise<Record<string, any>>;
